services:
  - type: web
    name: panaderia-pro
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d8bs2igjo6nc73eabj40-a.ohio-postgres.render.com:5432/panaderia_oof6?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: panaderia_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: s4b2pXoSK67FjNHbTcKMHjBtefzBx9iW
      - key: JWT_SECRET
        value: clave-super-secreta-panaderia-2024-muy-larga-para-seguridad
      - key: JWT_EXPIRATION
        value: "86400000"
